jqyang42/ht_buses

frontend/src/App.js
frontend/src/constants.js
frontend/src/templates/index.js
frontend/src/templates/parent-dashboard.js
frontend/src/templates/routes-detail.js
frontend/src/templates/routes-edit.js
frontend/src/templates/routes-planner.js
frontend/src/templates/routes.js
frontend/src/templates/schools-create.js
frontend/src/templates/schools-detail.js
frontend/src/templates/schools-edit.js
frontend/src/templates/schools.js
frontend/src/templates/students-detail.js
frontend/src/templates/students-edit.js
frontend/src/templates/students.js
frontend/src/templates/users-create.js
frontend/src/templates/users-detail.js
frontend/src/templates/users-edit.js
frontend/src/templates/users.js

Html create

---

backend/ht_buses_app/urls.py
backend/ht_buses_app/views.py
frontend/src/templates/schools-create.js
frontend/src/templates/students-detail.js

finished school create and schools detail connections + api naming convention in django

Axios details

---

backend/ht_buses_app/urls.py
backend/ht_buses_app/views.py

Added student addresses to route planner api with parent id to avoid address duplication for Maps API. Added tester API that retrieves all schools for react pagination testing.

Route planner update

---

backend/ht_buses_app/views.py
frontend/src/templates/routes/routes-detail.js
frontend/src/templates/routes/routes-edit.js
frontend/src/templates/tables/route-students-table.js
frontend/src/templates/tables/students-table.js
frontend/src/templates/tables/users-table.js
frontend/src/templates/users/users-create.js

change first/last names to name (lmk if i missed any)
also most set up for route edit is up except login needs to be connected

Axios views

---

backend/ht_buses_app/views.py

Removed pagination from general view pages api for frontend handling pagination.

Removed pagination from general view pages for frontend pagination

---

backend/ht_buses_app/views.py
frontend/src/templates/schools/schools.js
frontend/src/templates/tables/schools-table.js

Fixed API Bug where /users/ displayed incorrectly one of the fields and User Detail would not display a parent due to a missing serializer.

Fixed API Bug with Users/User Detail

---

backend/ht_buses_app/urls.py
backend/ht_buses_app/views.py

Completed views that parent users see with dashboard and their student detail view. Additionally modified login to return the user id from the table and to return is_staff for page redirection (view between parent and admin).

Parent View API

---

backend/ht_buses_app/views.py

Rewrote GET API's to return separate first/last name fields instead of just a name field.

Returned first/last name fields instead of name for GET API's

---

backend/ht_buses_app/views.py

Fixed bug in user delete API

---

frontend/src/templates/parent-view/parent-dashboard.js
frontend/src/templates/parent-view/parent-detail.js
frontend/src/templates/tables/parent-dashboard-table.js

connected parent dashboards and details

Parent views

---

frontend/src/templates/schools/schools-detail.js
frontend/src/templates/students/students-detail.js
frontend/src/templates/tables/routes-table.js
frontend/src/templates/tables/users-table.js
frontend/src/templates/users/users-detail.js
frontend/src/templates/users/users-edit.js
frontend/src/templates/users/users.js

fixed first name/last name and empty arrays

Table names

---

backend/ht_buses_app/views.py
frontend/src/constants.js
frontend/src/templates/routes/routes-planner.js
frontend/src/templates/schools/schools-detail.js
frontend/src/templates/tables/school-students-table.js

routes-planner connected with backend: table shows student data, create adds new route, dropdown updates with backend routes :)
also react-dom'd the file i think
note: dropdown assumes that routes can't be deleted while in the interface

Connect routes

---

backend/ht_buses_app/views.py
frontend/src/templates/routes/routes-planner.js
frontend/src/templates/students/students-edit.js
frontend/src/templates/users/users-create.js
frontend/src/templates/users/users-edit.js

finished custom drop down menus for all the sites (?) including routeplanner
none of the edit sites have been tested for handleSubmit to work'
it looks big but literally im jsut doing the same thing across them LOL

Dropdown menus

---

frontend/package-lock.json
frontend/package.json
frontend/src/templates/routes/routes-edit.js
frontend/src/templates/schools/schools-create.js
frontend/src/templates/schools/schools-edit.js
frontend/src/templates/students/students-edit.js
frontend/src/templates/users/users-create.js
frontend/src/templates/users/users-edit.js
frontend/src/templates/users/users-password.js

redirects forms to appropriate pages after submissions

Redirect after submit

---

backend/ht_buses_app/views.py

Changed the Route Detail API to have school id returned.

Route detail API change

---

frontend/src/templates/routes/routes-detail.js
frontend/src/templates/tables/route-students-table.js
frontend/src/templates/tables/students-table.js
frontend/src/templates/users/users-password.js

bug fixes for api/frontend stuff
editted /students to include school_student_id

Accordions (bug fixes)

---

frontend/src/templates/schools/schools-create.js
frontend/src/templates/schools/schools-edit.js
frontend/src/templates/users/users-create.js
frontend/src/templates/users/users-edit.js

adds autocomplete to appropriate places

Adding autocompletes

---

frontend/src/templates/students/students-edit.js
frontend/src/templates/users/users-create.js
frontend/src/templates/users/users-edit.js

delete added users working
user create definitely wokrs, user edit is unknown

Delete add user

---

backend/ht_buses_app/urls.py
backend/ht_buses_app/views.py

Added parameter for routes GET API and created a new API for routeplanner to edit a route by adding/removing students.

Added parameter for Kyra/route editing API for Thomas

---

backend/ht_buses_app/urls.py
frontend/src/templates/routes/map-marker.js
frontend/src/templates/routes/route-map.js
frontend/src/templates/routes/routes-planner.js
frontend/src/templates/users/users-edit.js

Sets up routeplanner to assign marker changes to specific ids and updates it in backend.

Google apis

---

frontend/src/templates/parent-view/parent-dashboard.js
frontend/src/templates/users/users-edit.js

Note: dashboard bug still exists

Frontend debug for email field error message

---

frontend/src/templates/routes/routes-planner.js

fix assign_mode not being exited after save

Assign mode swap fix

---

backend/ht_buses_app/urls.py

Forgot this one line rip

---

backend/ht_buses_app/views/users/user_create.py

Users Create API sends back the id of the newly created user.

Users Create API Modification

---

backend/ht_buses_app/views/routes/routes_view.py
backend/ht_buses_app/views/schools/school_create.py
backend/ht_buses_app/views/students/student_edit.py
backend/ht_buses_app/views/students/students_view.py

Fixed Route API bug that would not assign route_id properly and fixed missing parameters to school create API.

Fixed Route Bug/Added missing parameters to school create

---

backend/ht_buses_app/views/schools/school_create.py

Request 3 from backend-requests: have the POST method in schools_create return to me the school's new table ID so that i can redirect from schools_create to schools_detail

Added id parameter to Schools Create API

---

frontend/src/templates/users/users-detail.js

add student working, and delete and edit and change pw
still needed:
- add red * to student id (form already knows its required)

Detail test - user-details should be fully good

---

frontend/src/templates/schools/schools-detail.js
frontend/src/templates/students/students-detail.js

student deletion wokring but needs some more help with rerouting - after rerouting the screen stays dark?

Detail test - deletion working

---

backend/ht_buses_app/views/routes/route_detail.py

Bug fixed in route_detail where each parent would show all the kids, not just their kids only.

Bug fixed in route_detail

---

frontend/src/templates/routes/routes-detail.js
frontend/src/templates/routes/routes.js
frontend/src/templates/students/students-edit.js
frontend/src/templates/tables/routes-table.js

routes student table showing student, delete working but really ugly

Routes shit

---

backend/ht_buses_app/views/routes/route_planner.py

Routeplanner GET API now sends the first name and last name of each student.

Routeplanner GET sents first_name/last_name

---

backend/ht_buses_app/views/auth/auth_valid.py
backend/ht_buses_app/views/parents/parent_dashboard.py
backend/ht_buses_app/views/parents/parent_student_detail.py
backend/ht_buses_app/views/routes/route_create.py
backend/ht_buses_app/views/routes/route_delete.py
backend/ht_buses_app/views/routes/route_detail.py
backend/ht_buses_app/views/routes/route_edit.py
backend/ht_buses_app/views/routes/route_planner.py
backend/ht_buses_app/views/schools/school_delete.py
backend/ht_buses_app/views/schools/school_detail.py
backend/ht_buses_app/views/schools/school_edit.py
backend/ht_buses_app/views/students/student_add.py
backend/ht_buses_app/views/students/student_delete.py
backend/ht_buses_app/views/students/student_detail.py
backend/ht_buses_app/views/students/student_edit.py
backend/ht_buses_app/views/students/student_route_edit.py
backend/ht_buses_app/views/users/user_delete.py
backend/ht_buses_app/views/users/user_detail.py
backend/ht_buses_app/views/users/user_edit.py
backend/ht_buses_app/views/users/user_edit_password.py

Added 400 and 404 response codes to GET/PUT/POST/DELETE methods if the api fails to update/create/delete/or find a record in the database.

Added 400/404 to GET/PUT/POST/DELETE methods

---

backend/ht_buses_app/views/resources/capitalize_reg.py
backend/ht_buses_app/views/routes/route_create.py
backend/ht_buses_app/views/routes/route_edit.py
backend/ht_buses_app/views/schools/school_create.py
backend/ht_buses_app/views/schools/school_edit.py
backend/ht_buses_app/views/students/student_create.py
backend/ht_buses_app/views/students/student_edit.py
backend/ht_buses_app/views/users/user_create.py
backend/ht_buses_app/views/users/user_edit.py

Fixed capitalization for route name, school name, student name, and admin/parent names where it only capitalizes the first letter of each word using regex.

Fixed capitalization

---

frontend/src/templates/users/users-edit.js

radio buttons should work like actual buttons now hehe

fixed weird radio buttons in user edit

---

backend/ht_buses_app/views/parents/parent_student_detail.py

Fixed bug on parent detail where student with no route id was breaking :,)

Fixed bug on parent detail where student with no route id was breaking

---

backend/ht_buses_app/views/routes/route_create.py

Debugging Regex using idea from Anshu

Debug Regex

---

backend/ht_buses_app/views/routes/route_create.py

undoing anshu change lmfao bc my stuff thankfully works

Undo Anshu change

---

backend/ht_buses_app/views/parents/parent_dashboard.py

Added student_school_id to parent dashboard api.

Added student_school_id to parent dashboard api

---

backend/ht_buses_app/views/auth/logout.py
backend/ht_buses_app/views/students/student_delete.py
backend/ht_buses_app/views/users/user_detail.py
frontend/src/templates/users/users-create.js
frontend/src/templates/users/users-detail.js
frontend/src/templates/users/users-edit.js

Need to test token bug on prod still 
#193

Fixed address change, student deletion, and token? bugs

---

frontend/src/templates/components/dropdown.js
frontend/src/templates/components/helper.js
frontend/src/templates/components/validation.js
frontend/src/templates/regex/input-validation.js
frontend/src/templates/students/students-edit.js
frontend/src/templates/users/users-create.js
frontend/src/templates/users/users-detail.js
frontend/src/templates/users/users-edit.js
frontend/src/templates/users/users.js

refactored all users pages except users-passwords (not hooked up yet)
should be following  general flow of:
componentdidmount
api calls
render handlers/helper functions
validation methods and schools/routes dropdowns refactored to separate component
cleaned up state to pretty much match json formatting + made setstate calls consistent
also fixed bug where delete students in accordion looked weird (but worked right)

Refactor frontend users

---

frontend/src/templates/parent-view/parent-dashboard.js
frontend/src/templates/parent-view/parent-detail.js

Refactor frontend parent

---

backend/ht_buses_app/views/schools/school_detail.py
backend/ht_buses_app/views/schools/schools_view.py

- Closes #213: removes the seconds for school times to be displayed on school details and school view.

Removed seconds from arrival/departure times for schools

---

backend/ht_buses_app/examples/students/requests/student_route_edit_request.json
backend/ht_buses_app/examples/students/responses/student_route_edit_response.json
backend/ht_buses_app/views/students/student_route_edit.py

Fixed a bug with adding a route to a student via the routeplanner edit API. Added JSOn example for the routeplanner edit API. Really need to proofread next time LOL cannot spell nowadays

Bug Fix: /api/routeplanner/edit API

---

frontend/src/templates/routes/routes-planner.js

closes #171 
and refactored api calls a littol in routeplanner

route add sshould be working + refactoring

---

backend/ht_buses_app/examples/stops/errors/stops_create_error.json
backend/ht_buses_app/examples/stops/errors/stops_view_error.json
backend/ht_buses_app/examples/stops/requests/stops_create_request.json
backend/ht_buses_app/examples/stops/responses/stops_create_response.json
backend/ht_buses_app/examples/stops/responses/stops_view_response.json
backend/ht_buses_app/examples/users/response/user_detail_response.json
backend/ht_buses_app/serializers.py
backend/ht_buses_app/urls.py
backend/ht_buses_app/views/stops/stops_create.py
backend/ht_buses_app/views/stops/stops_view.py
backend/ht_buses_app/views/users/user_detail.py

Created Stop GET/CREATE API's, modified User Detail View API to return school id and school name.

Stop GET/CREATE API

---

backend/ht_buses_app/views/routes/route_detail.py
backend/ht_buses_app/views/schools/school_detail.py

Added in_range to school detail/route detail api.

Adding in_range to school detail/route detail

---

frontend/src/templates/routes/route-map.js
frontend/src/templates/routes/routes-planner.js

Refreshes stops state when assign mode save button is pressed.

renders stop markers from backend

---

backend/ht_buses_app/examples/parents/parent_student_detail_response.json
backend/ht_buses_app/views/parents/parent_student_detail.py
backend/ht_buses_app/views/stops/check_in_range.py

Added stops that are in_range for students of a parent for parent student detail api. Updated the json for parent student detail response to grab information.

Added stops in_range for students in parent student detail api

---

backend/ht_buses_app/examples/parents/parent_student_detail_response.json
backend/ht_buses_app/examples/stops/requests/stops_edit_request.json
backend/ht_buses_app/views/parents/parent_student_detail.py
backend/ht_buses_app/views/stops/stops_edit.py

Parent Student Detail API now sends back the address of the student (address/lat/long) and the Stop Edit API now takes in the address. JSON's have been updated for both API's.

Parent Student Detail API/Stop Edit API

---

backend/ht_buses_app/views/stops/stops_edit.py

Fixed location update error in stop edit API.

Fixed location update error

---

frontend/src/templates/routes/route-map.js
frontend/src/templates/routes/route-time-calc.js
frontend/src/templates/routes/routes-planner.js
frontend/src/templates/tables/stops-table.js
frontend/src/templates/tables/table.js

- stops table: sorts rows by hidden column using `order_by` accessor
- stop times should be updating now :))

Stops hidden column

---

backend/ht_buses_app/examples/stops/requests/stops_edit_name_request.json
backend/ht_buses_app/views/stops/stops_name_edit.py

Edited the Stop API to take lat/long

Edited Stop API to take lat/long

---

backend/ht_buses_app/views/stops/stops_name_edit.py
frontend/src/templates/routes/route-map.js
frontend/src/templates/routes/stop-marker.js

woooo yea baby thats what we're waiting for thats what its all about woooo

drag and drop for stops lets fucking gooooooooooooooooooooooooooooooo

---

backend/ht_buses_app/views/stops/stops_edit.py
backend/ht_buses_app/views/stops/stops_name_edit.py

Bug fix for when a student marker is added near student but route is not completed, bug where if you edit a stop near student through dragging student does not get moved to out of range status.

EMERGENCY BUGFIX: Incomplete not updating on Route/Student wasn't being updated to in_range

---

backend/ht_buses_app/examples/stops/responses/stops_view_response.json
backend/ht_buses_app/views/stops/stops_view.py

Added route is_complete field to the Stop View API.

Stop View API: Added route is_complete

---

frontend/src/templates/components/time.js
frontend/src/templates/routes/route-time-calc.js
frontend/src/templates/routes/routes-planner.js

time calculation is correct yay

New latlong update

---

backend/ht_buses_app/views/routes/route_delete.py
backend/ht_buses_app/views/routes/search/route_search.py
backend/ht_buses_app/views/routes/sorting/route_sorting.py
backend/ht_buses_app/views/schools/search/school_search.py
backend/ht_buses_app/views/schools/sorting/school_sort.py
backend/ht_buses_app/views/students/search/student_search.py
backend/ht_buses_app/views/students/sorting/student_sorting.py
backend/ht_buses_app/views/users/search/user_search.py
backend/ht_buses_app/views/users/sorting/user_sort.py

Bug fixed for search, now it finds everything across all search :)
Fixed bug where if a route was deleted on a student in range, in range value stays true.

BUGFIX: Search

---

backend/ht_buses_app/views/students/student_detail.py

Student Detail now gives parent information fields: See ticket to see formatting for return #418

Student Detail gives Parent Info

---

backend/ht_buses_app/views/students/student_pagination.py

Updated Student Table API for big student table to return phone number of the parent. Part of #417

Student Table API (Main Student Page): Phone Number Update

---

backend/ht_buses_app/views/users/users_view.py

Fixed Role Search bug that Thomas was encountering.

Fixed search for roles

---

backend/ht_buses_app/views/users/users_view.py

Fixed error with role seach should fully work now :,,,)

Fixed error with Q error

---

frontend/src/templates/tables/users-table.js

fixes Issue 422: users table sorts role only by asc

---

backend/ht_buses_app/views/students/students_view.py

Fixed bug where you could see all users in a flash haha ty fern :)

Fixed student table bug

---

frontend/src/templates/routes/routes.js
frontend/src/templates/schools/schools.js
frontend/src/templates/students/students.js
frontend/src/templates/users/users.js

users, students, routes, schools pages no longer double-calling to populate the table upon load

Multiple calls

---

frontend/src/templates/students/students.js
frontend/src/templates/users/users.js

fix bug for file import same file with error. change headers in error message.

---

frontend/src/templates/students/students-import.js
frontend/src/templates/users/users-import.js

sorting errors by row num

---

backend/ht_buses_app/views/bulk_import/upload/bulk_import_view_students.py
backend/ht_buses_app/views/bulk_import/upload/bulk_import_view_users.py
backend/ht_buses_app/views/bulk_import/validation/bulk_import_validate_students.py
backend/ht_buses_app/views/bulk_import/validation/bulk_import_validate_users.py

This bug tis sad

---

frontend/src/templates/components/email.js
frontend/src/templates/routes/routes-detail.js
frontend/src/templates/students/students-import.js
frontend/src/templates/users/users-import.js

Add misc info banners to frontend

---

backend/ht_buses_app/views/buses/bus_management.py

Bugfix for the active_buses method, accidentally forgot the whole variable hehe.

BUGFIX: Found a typo in active_buses method

---

backend/ht_buses_app/urls.py
backend/ht_buses_app/views/logs/detail/log_driver_view.py
backend/ht_buses_app/views/logs/detail/log_route_view.py
backend/ht_buses_app/views/logs/detail/log_school_view.py
backend/ht_buses_app/views/logs/log_pagination.py

Changes to Log API's:
- Global Log API now returns color id for the route
- Addition of Log API based on Route
- Addition of Log API based on School
- Addition of Log API based on Driver

Log API Updates: Gloabl Log/Route Log/School Log/Driver Log

---

backend/ht_buses_app/urls.py
backend/ht_buses_app/views/routes/route_transit.py
backend/ht_buses_app/views/users/user_transit.py

Route in-transit and Driver in-transit API complete.

Route in-transit API/Driver in-transit API

---

backend/ht_buses_app/urls.py
backend/ht_buses_app/views/buses/bus_view.py
backend/ht_buses_app/views/logs/log_pagination.py
backend/ht_buses_app/views/logs/log_view.py

Global Log API has been updated with new parameter called active to get active logs and new API that gives the bus number.

Active Log/Bus GET Method

---

backend/ht_buses_app/urls.py
backend/ht_buses_app/views/buses/bus_active_view.py
backend/ht_buses_app/views/buses/bus_view.py
backend/ht_buses_app/views/routes/route_transit.py
backend/ht_buses_app/views/users/user_transit.py

Added the Active Buses GET API which returns bus number, coords, and driver name. Did nit fixes to the other methods because I forgot a corner case oop

Active Buses GET API

---

backend/ht_buses_app/views/buses/bus_active_view.py

Update to the Bus View API that returns the schools and center lat/lng for the map.
JSON example:
```
{
"buses": [
{
"bus_number": 121,
"location": {
"id": 9,
"lat": 0.0,
"lng": 0.0
},
"user": {
"id": 3,
"first_name": "Driver",
"last_name": "Example"
}
}
],
"schools": [
{
"id": 1,
"school": "Duke University",
"location": {
"lat": 35.9976886,
"lng": -78.9325993
}
}
],
"center": {
"lat": 35.9976886,
"lng": -78.9325993
}
}
```

Bus View API: Update

---

backend/ht_buses_app/views/buses/bus_active_view.py
backend/ht_buses_app/views/logs/log_create.py
backend/ht_buses_app/views/logs/log_update.py
frontend/src/templates/routes/routes-detail.js

Added an update to `http://localhost:8000/api/buses/school?id=5` that handles error checking if school id does not exist, for global (id=0) it returns all schools

Bus API Update: Returns all schools

---

backend/ht_buses_app/urls.py
backend/ht_buses_app/views/buses/bus_active_route_view.py
backend/ht_buses_app/views/logs/detail/log_school_view.py

This PR add the active field for log schools and have active buses for a specific route

Changed log school to be active, made bus for route

---

backend/ht_buses_app/views/logs/log_view.py
backend/ht_buses_app/views/students/detail/student_view_user.py
backend/ht_buses_app/views/students/students_view.py

Fixed sorting logs for sorting by start_time, very hacky do not recommend

Fix sorting logs: sort by start_time working

---

backend/ht_buses_app/urls.py
backend/ht_buses_app/views/buses/bus_all_schools_view.py

-Added new api that grabs all schools and restricts for school staff called `blah-blah/api/buses/all-schools`

Added all schools api

---

backend/ht_buses_app/views/buses/bus_all_schools_view.py

Fixed center calculation on the new api for all schools, forgot to divide oop

Fixed center calc

---

backend/ht_buses_app/views/buses/bus_all_schools_view.py

Buses school all

---

backend/ht_buses_app/views/buses/bus_all_schools_view.py

LOL I had syntax errors she is fixed haha

Fixing bug for all schools

---

backend/ht_buses_app/serializers.py
backend/ht_buses_app/views/logs/log_view.py
backend/ht_buses_app/views/students/students_view.py
backend/ht_buses_app/views/users/user_delete.py
backend/ht_buses_app/views/users/users_view.py

Fixes sorting from only using first_name to full_name for users, students, and logs for driver name. Also contains bug fix for deleting student user when a parent is deleted.

BUGFIX: Fixes Sorting from first_name to full_name and student deletion from parent deletion

---

frontend/src/templates/tables/global-transit-log-table.js
frontend/src/templates/tables/server-side-pagination.js
frontend/src/templates/users/users-detail.js

- school dropdown for add student on user-details now defaulting to select school

Ev4 frontend bug fixes

---

backend/ht_buses_app/views/announcements/announcements.py
backend/ht_buses_app/views/general/general_tools.py

Fixed announcement problemos :)

Announcement school fix

---

backend/ht_buses_app/views/announcements/announcements.py
backend/ht_buses_app/views/general/general_tools.py

Fixed helper method to not break other methods heh

Fixed helper method

---

frontend/src/static/custom.css
frontend/src/templates/routes/route-map.js
frontend/src/templates/routes/routes-detail.js
frontend/src/templates/routes/routes-planner.js
frontend/src/templates/routes/stop-marker.js
frontend/src/templates/routes/student-marker.js

hopefully bletsch does not complain

fix css layout for route stuff

---

frontend/src/templates/routes/route-map.js
frontend/src/templates/routes/routes-detail.js
frontend/src/templates/routes/routes-planner.js
frontend/src/templates/routes/school-marker.js
frontend/src/templates/schools/schools-transit-status.js

honestly dont know what's different between here and dev but routeplanner shows up on this branch now at least

I guess I updated some stuff that got the map to show on routeplanner???

---

backend/ht_buses_app/views/logs/log_pagination.py

I added seconds back lmfao

---

backend/ht_buses_app/views/buses/bus_all_schools_view.py

all school api now goes and checks for each school

Emmy fixes thingz: all school api

---

backend/ht_buses_app/views/bulk_import/upload/bulk_import_view_students.py
backend/ht_buses_app/views/bulk_import/validation/bulk_import_validate_students.py

When you uploaded/validated a student csv with an invalid email, the error was not being flagged

Fixed bulk import for invalid student email
